version: 2.1

executors:
  python-executor:
    working_directory: ~/phovea
    docker:
      - image: circleci/python:3.7-buster-node-browsers # for node version see Dockerfile on https://hub.docker.com/r/circleci/python
  node-executor:
    working_directory: ~/phovea
    docker:
      - image: circleci/node:12.13-buster-browsers

jobs:
  python-build:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Show Node.js and npm version
          command: |
            node -v
            npm -v
      - run:
          name: Show Python and pip version
          command: |
            python --version
            pip --version
      - run:
          name: Install Docker packages from docker_packages.txt
          command: |
            (!(test -f docker_packages.txt) || (cat docker_packages.txt | xargs sudo apt-get install -y))
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}
      - run:
          name: Install pip requirements
          command: |
            virtualenv ~/venv
            . ~/venv/bin/activate
            pip install -r requirements_dev.txt
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}
          paths:
          - ~/venv
      - run:
          name: Force an update of pip dependencies from git repositories # not sure if this is working ?
          command: |
            . ~/venv/bin/activate
            pip install --upgrade --upgrade-strategy=only-if-needed -r requirements.txt
      - run:
          name: Show installed pip packages
          command: pip list || true
      - run:
          name: Build
          command: |
            . ~/venv/bin/activate
            npm run dist
      - store_artifacts:
          path: dist
          destination: dist
      - persist_to_workspace:
          root: ~/phovea
          paths: .
  python-publish:
    executor: python-executor
    steps:
      - attach_workspace:
          at: ~/phovea
      - run:
          name: Install twine
          command: |
            . ~/venv/bin/activate \
            pip install twine \
      - run:
          name: Authentication
          command:  |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "repository = $PYPI_REPOSITORY" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: Publish package
          command: |
            . venv/bin/activate
            twine upload dist/*
  web-build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Show Node.js and npm version
          command: |
            node -v
            npm -v
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Remove npm dependencies installed from git repositories (avoid caching of old commits)
          command: |
            (grep -l '._resolved.: .\(git[^:]*\|bitbucket\):' ./node_modules/*/package.json || true) | xargs -r dirname | xargs -r rm -rf
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
          paths: ./node_modules
      - run:
          name: Install npm dependencies from git repositories (always get latest commit)
          command: npm install
      - run:
          name: Show installed npm dependencies
          command: npm list --depth=1 || true
      - run:
          name: Build
          command: npm run dist
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: ~/phovea
          paths: .
  web-publish:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/phovea
      - run:
          name: Authentication
          command:  |
            echo -e "registry=https://$NPM_REPOSITORY" >> ~/phovea/.npmrc
            echo -e "//$NPM_REPOSITORY:authToken=$NPM_TOKEN" >> ~/phovea/.npmrc
      - run:
          name: Publish package
          command: npm publish
workflows:
  version: 2.1
#  build-nightly:
#    triggers:
#      - schedule:
#          cron: "15 1 * * 1-5" # "At 01:15 on every day-of-week from Monday through Friday.‚Äù, see: https://crontab.guru/#15_1_*_*_1-5
#          filters:
#            branches:
#              only:
#                - develop
#    jobs:
#      - python-build
#      - web-build
  build-branches-only:
    jobs:
      - python-build:
          filters:
            tags:
              ignore: /.*/
      - web-build:
        filters:
          tags:
            ignore: /.*/
  build-publish-tag:
    jobs:
      - python-build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - web-build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - python-publish:
          context:
              - org-public
          requires:
              - python-build
              - web-build
          filters:
              branches:
                ignore: /.*/
              tags:
                only: /^v.*/
      - web-publish:
          context:
              - org-public
          requires:
              - python-build
              - web-build
          filters:
              branches:
                ignore: /.*/
              tags:
                only: /^v.*/
